version: '3.8'

services:
  quotient-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - PORT=8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./server.py
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock 